<?php
$out = [];
foreach ($all as $fd) {
    $out[] = "'" . $fd['column_name'] . "'";
}
if ($pk == null) {
    // $f = explode(',', $out);
    $pk = str_replace("'", "", array_shift(($out)));
}
$string = "<?php namespace App\Models;

use CodeIgniter\Model;

class $m extends Model
{
    protected \$table      = '$table_name';
    protected \$primaryKey = '$pk';
    protected \$allowedFields = [";

$string .= implode(',', $out);


$string .= "]; 

    // GET ALL DATA
    public function getData(\$id = false)
    {
        if (\$id == false) {
            return \$this->findAll();
        }
        return \$this->db->where(\$this->primaryKey, \$id)->first();
    }
";
$string .= "\n\n}\n\n/* End of file $m_file */
/* Location: ./app/models/$m_file */
 /* Generated by CX-CRUD " . date('Y-m-d H:i:s') . " */";


$result_model = createFile($string, $target . "models/" . $m_file);
