<?php namespace App\Controllers;
/**
* THIS CONTROLER CODEIGNITER 4
* Codeigniter Version 4.x
* Generated by LigatCode
**/
use App\Models\CategoriasModel;
use CodeIgniter\HTTP\Response;

class Categorias extends BaseController
{
    /**
	 * Class constructor.
     */	
    protected $PageData;
    protected $Model; //Default Models Of this Controler
    protected $pager;
	public function __construct()
	{
		$this->Model = new CategoriasModel(); //Set Default Models Of this Controler
        $this->PageData = $this->attributePage(); //Attribute Of Page
    }
    
    //ATRIBUTE THIS PAGE
    private function attributePage()
	{
		return  [
			'title' => 'LigatCode | Categorias',
			'app' => 'LigatCode',
		];
    }

    //INDEX 
    public function index()
	{
		$data = [
			'AttributePage' =>$this->PageData,
			'content' => 'Create Pages',
           ];
		return view('categorias/index_categorias', $data);
    }


public function fetchExpenses()
{
    $request = service('request');
    

    $draw = $request->getPost('draw');
    $start = intval($request->getPost('start')); // Convertir a entero
    $length = intval($request->getPost('length')); // Convertir a entero
    $searchValue = $request->getPost('search')['value'];

    $order = $request->getPost('order');
    $orderColumn = $order[0]['column'];
    $orderDir = $order[0]['dir'];
    $columns = $request->getPost('columns');
    $orderBy = $columns[$orderColumn]['data'];

    $query = $this->Model;

    if (!empty($searchValue)) {
        $query->like('id', $searchValue);
					    $query->orLike('id', $searchValue);
					    $query->orLike('nombre', $searchValue);
					    $query->orLike('descripcion', $searchValue);
					    $query->orLike('fecha', $searchValue);}

    $totalFiltered = $query->countAllResults(false);

    $query->orderBy($orderBy, $orderDir)
          ->limit($length, $start); // Asegúrate de que ambos son enteros

    $results = $query->findAll();
    $totalData = $this->Model->countAll();

    $response = [
        'draw' => intval($draw),
        'recordsTotal' => $totalData,
        'recordsFiltered' => $totalFiltered, 
         'data' => $results, ];

    return $this->response->setJSON($response);
}



    //READ
    public function read($id)
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Read Pages',
			'data' => $this->Model->find($id) //find on data
		];
		return view('categorias/read_categorias', $data);
    }

    //CREATE
    public function create()
	{
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Create Pages',
			'action' => 'Categorias/create_action',
			'data' =>   [
					     'id' => set_value('id'),
					     'nombre' => set_value('nombre'),
					     'descripcion' => set_value('descripcion'),
					     'fecha' => set_value('fecha'),
					    ]
		];
		return view('categorias/form_categorias', $data);
    }	

    //ACTION CREATE
	public function create_action()
	{

    $validation = \Config\Services::validation(); 
		$validation->setRules($this->_rules()); 
		if (!$validation->withRequest($this->request)->run()) 
		{ 
	return redirect()->back()->withInput()->with('errors', $validation->getErrors()); 
	} $data =[
					     'id' => $this->request->getVar('id'),
					     'nombre' => $this->request->getVar('nombre'),
					     'descripcion' => $this->request->getVar('descripcion'),
					     'fecha' => $this->request->getVar('fecha'),
        
				];
		$this->Model->save($data);
		session()->setFlashdata('message', 'Create Record Success');
		return redirect()->to(base_url('/Categorias'));
    }
    
    //UPDATE
	public function update($id)
	{
		$dataFind = $this->Model->find($id);
		if($dataFind == false){
			return redirect()->to(base_url('/Categorias'));
		}
		$data = [
			'AttributePage' => $this->PageData,
			'content' => 'Edite Pages',
			'action' => 'categorias/update_action',
			'data' => $this->Model->find($id),
        ];
		session()->setFlashdata('message', 'Update Record Success');
		return view('categorias/form_categorias', $data);
    }
    
    //ACTION UPDATE
   	public function update_action()
	{

       $validation = \Config\Services::validation(); 
		$validation->setRules($this->_rules()); 
		if (!$validation->withRequest($this->request)->run()) { 
	          return redirect()->back()->withInput()->with('errors', $validation->getErrors()); 
	    }

		$id = $this->request->getVar('id');
		$row = $this->Model->find($id); 

        if (!$row) {
            session()->setFlashdata('error', 'Registro no encontrado.');
            return redirect()->to(base_url('categorias'));
        }  
$data =[
					     'id' => $id,
					     'nombre' => $this->request->getVar('nombre'),
					     'descripcion' => $this->request->getVar('descripcion'),
					     'fecha' => $this->request->getVar('fecha'),
                    ];

        if ($this->Model->save($data)) {
                   session()->setFlashdata('message', 'Update Record Success');
        } else {
                   session()->setFlashdata('error', 'Error al actualizar el registro.');
    }
			
			return redirect()->to(base_url('categorias'));
		
	}

    //DELETE
	public function delete($id)
	{
		$row = $this->Model->find(['id' => $id]);
		if ($row) {
            $this->Model->delete($id);
            session()->setFlashdata('message', 'Delete Record Success');
            return redirect()->to(base_url('/categorias'));
        } else {
            session()->setFlashdata('message', 'Record Not Found');
            return redirect()->to(base_url('/categorias'));
        }

    }

    //RULES
    public function _rules() 
    { 
    return [
	'nombre' => 'trim|required',
	'descripcion' => 'trim|required',
	'fecha' => 'trim|required', ]; 
}

}

/* End of file Categorias.php */
 /* Location: ./app/controllers/Categorias.php */
 /* Please DO NOT modify this information : */
 /* Generated by Ligatcode Codeigniter 4 CRUD Generator 2024-11-26 12:58:47 */