<?php namespace App\Models;

use CodeIgniter\Model;

class ClientesModel extends Model
{
    protected $table      = 'clientes';
    protected $primaryKey = 'id';
    protected $allowedFields = ['id','nombre','email','telefono','direccion','fecha_nacimiento','file']; 

    // GET ALL DATA
    public function getData($id = false)
    {
        if ($id == false) {
            return $this->findAll();
        }
        return $this->db->where($this->primaryKey, $id)->first();
    }


}

/* End of file ClientesModel.php */
/* Location: ./app/models/ClientesModel.php */
 /* Generated by CX-CRUD 2024-11-26 13:52:30 */